Algoritmo "Concatenação"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Concatenação
// Autor(a)    : Denner Diniz
// Data atual  : 8/31/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o nome: ")
   leia(nome)
   escreval("Digite o numero: ")
   leia(numero)

   escreval(nome, numero)

Fimalgoritmo