Algoritmo "Operadores Relacionais"

// Descrição   : Operadores Relacionais
// Autor(a)    : Denner Diniz
// Data atual  : 8/31/2020
Var
// Seção de Declarações das variáveis 
   nota01, nota02: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota01 :=10
   nota02 :=15
   
   se (nota01 <> nota02) entao
      escreval("Diferente")
   senao
      escreval("Igual")
   fimse

Fimalgoritmo