Algoritmo "Variáveis"
// Disciplina   : [Lógica e algorítimo]
// Professor   : Cleison Ferreira de Melo
// Descrição   : Tipos de variáveis
// Autor(a)    : Denner Diniz Soares Santos
// Data atual  : 8/25/2020
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço
          primeiroNome, segundoNome, cidade, endereco: caractere;
          idade: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo